#! /usr/bin/env bash

WG_DIR="/etc/wireguard/"
PORT=$(shuf -n 1 -i 10000-65535)
# IPv6Prefix="fd00::"
TEMPLATEURL="https://raw.githubusercontent.com/finzzz/wgzero/master/template"

GRAY="$(tput setaf 8)"
RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
ORANGE="$(tput setaf 3)"
CYAN="$(tput setaf 6)"
NC="$(tput sgr0)"

Run(){
    IsRoot
    CheckPackages "wg iptables curl qrencode jq"
    EnableIPForward

    case "$1" in
    "install")
        # ./wgzero install
        Install ;;
    "import")
        # ./wgzero import wg0.conf
        Import "$@" ;;
    "list")
        # ./wgzero list <wg_interface=wg0>
        List | column -t -s, 2>/dev/null
        echo -en "${NC}" ;;
    "add")
        # ./wgzero add <client_name> <wg_interface=wg0>
        Add "$@" ;;
    "del")
        # ./wgzero delete <client_name> <wg_interface=wg0>
        Del "$@" ;;
    "edit")
        # ./wgzero edit server <wg_interface=wg0>
        # ./wgzero edit <client_name> <wg_interface=wg0>
        Edit "$@" ;;
    "enable")
        # ./wgzero enable <client_name> <wg_interface=wg0>
        ModifyClientEntry "$2" "s/^#//" ;;
    "disable")
        # ./wgzero disable <client_name> <wg_interface=wg0>
        ModifyClientEntry "$2" "s/^[^#]./#&/" ;;
    "qr")
        # ./wgzero qr <client_name> <wg_interface=wg0>
        ShowQR "$2" ;;
    "postup")
        # ./wgzero postup <wg_interface>
        INTERFACE="eth0"
        TYPE="v4"
        /usr/sbin/iptables -t nat -A POSTROUTING -o "$INTERFACE" -j MASQUERADE
        if [ "$2" == "nat" ]; then
            /usr/sbin/ip6tables -t nat -A POSTROUTING -o "$INTERFACE" -j MASQUERADE
        elif [ "$2" == "fr" ]; then
            /usr/sbin/ip6tables -A FORWARD -i "$3" -j ACCEPT
        fi
        ;;
    "postdown")
        # ./wgzero postdown <wg_interface>
        INTERFACE="eth0"
        TYPE="v4"
        /usr/sbin/iptables -t nat -D POSTROUTING -o "$INTERFACE" -j MASQUERADE
        if [ "$2" == "nat" ]; then
            /usr/sbin/ip6tables -t nat -D POSTROUTING -o "$INTERFACE" -j MASQUERADE
        elif [ "$2" == "fr" ]; then
            /usr/sbin/ip6tables -D FORWARD -i "$3" -j ACCEPT
        fi
        ;;
    *)
        Print "Unknown command\\n" "red" ;;
    esac
}

### PRECHECKS ###
IsRoot(){
    if [[ ! "$EUID" -eq 0 ]]; then
        Print "Must be run as root\\n" "red" && exit
    fi
}

CheckPackages(){
    for i in $1; do 
        if [[ ! $(command -v "$i") ]]; then
            Print "$i: command not found, please check required packages.\\n" "red" && exit
        fi
    done
}

EnableIPForward(){
    sed -i 's/\#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
    echo 1 > /proc/sys/net/ipv4/ip_forward
    
    # IPv6
    sed -i 's/\#net.ipv6.conf.all.forwarding=1/net.ipv6.conf.all.forwarding=1/' /etc/sysctl.conf
    echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
    
    /usr/sbin/sysctl -p -q
}
###

Print(){
    case "$2" in
    "red")
        echo -en "${RED}$1${NC}";;
    "cyan")
        echo -en "${CYAN}$1${NC}";;
    "orange")
        echo -en "${ORANGE}$1${NC}";;
    "gray")
        echo -en "${GRAY}$1${NC}";;
    *)
        echo -en "${GREEN}$1${NC}";;
    esac
}

ReadInput(){
    read -rp "${ORANGE}$1 [$2]: ${NC}" VAL
    VAL=${VAL:-"$2"}
}

ReadConfig(){
    # ReadConfig section wg0
    grep "$1 = " "/etc/wireguard/$2" | cut -d "=" -f 2 | tr -d " "
}

WriteConfig(){
    # WriteConfig section default_val wg0
    ReadInput "$1" "$2"
    sed -i "s/$1 =.*/$1 = $VAL/g" "/etc/wireguard/$3.conf"
}

GeneratePublicKey(){
    # GeneratePublicKey privatekey
    /usr/bin/wg pubkey <<< "$1"
}

### INSTALL ###
GenerateConfig(){
    # GenerateConfig wg0
    CFG="/etc/wireguard/$1.conf"
    if [ -f "$CFG" ]; then
        ReadInput "Config file $CFG already exists, do you want to overwrite" "y/N"
        if [ "$VAL" == "y" ]; then
            rm "$CFG"
            ip link del "$1" 2>/dev/null
        else
            exit
        fi
    fi
    
    curl -so "$CFG" "$TEMPLATEURL/wg0.conf"
    sed -i "s/WG_INTERFACE/$1/g" "$CFG"
    chmod 600 "$CFG"
}

SetInterface(){
    # SetInterface wg0
    INTERFACES=$(ip -json l | jq -r '.[]|.ifname' | grep -v lo)
    DEFAULT=$(echo "$INTERFACES" | head -1)

    Print "Available interfaces :\\n" "cyan" && echo "$INTERFACES"
    WriteConfig "Interface" "$DEFAULT" "$1"
}

Install(){
    ReadInput "Wireguard Interface Name" "wg0" && WG="$VAL"
    GenerateConfig "$WG"
    SetInterface "$WG"
    WriteConfig "Endpoint" "$(curl -s ip.me)" "$WG"
    WriteConfig "ListenPort" "$PORT" "$WG"
    WriteConfig "Address" "10.10.0.1/24" "$WG"
    WriteConfig "MTU" "1420" "$WG"
    WriteConfig "Client MTU" "unset" "$WG"
    WriteConfig "DNS" "unset" "$WG"
    WriteConfig "KeepAlive" "unset" "$WG"

    # Generate Private Key
    PRIVKEY=$(/usr/bin/wg genkey)
    ReadInput "Specify private key" "none"
    [ "$VAL" != "none" ] && PRIVKEY="$VAL"
    sed -i "s/PrivateKey =.*/PrivateKey = $PRIVKEY/g" "/etc/wireguard/$WG.conf"

    TYPE="v4"
    ReadInput "Enable IPv6" "y/N"
    if [ "$VAL" == "y" ]; then
        TYPE="nat"
        WriteConfig "IPv6 Prefix" "fd00::" "$WG"
        WriteConfig "IPv6 Subnet" "64" "$WG"

        IPv6Prefix="$(ReadConfig 'IPv6 Prefix' $WG)"
        IPv6Subnet="$(ReadConfig 'IPv6 Subnet' $WG)"

        Print "External routing: \\n" "orange"
        Print "[1] NAT\\n" "cyan"
        Print "[2] Full Routing\\n" "cyan"
        ReadInput "Selection" "1"

        if [ "$VAL" == "2" ]; then
            TYPE="fr" 

            ReadInput "Configure ndppd" "y/N"
            if [ "$VAL" == "y" ]; then
                CheckPackages ndppd

                curl -so /etc/ndppd.conf "$TEMPLATEURL/ndppd.conf"
                sed -i -e "s/IFACE/$IPv6Prefix/g" /etc/ndppd.conf
                sed -i -e "s/PREFIX/$IPv6Subnet/g" /etc/ndppd.conf
                systemctl enable ndppd.service
                systemctl restart ndppd.service
            fi
        fi

        SetClientIPv6
        IPv6Addr="$IPv6Prefix$VAL/$IPv6Subnet"
        sed -i "s/Address =.*/&, $IPv6Addr/g" "/etc/wireguard/$WG.conf"
    fi
    
    wg-quick up "$WG" 2>/dev/null
    systemctl enable wg-quick@"$WG"

    Print "Done, make sure $(ReadConfig ListenPort $WG)/UDP is open\\n" "red"
}
###

PrintIPs() {
    # PrintIPs 10.0.0.0/24
    BASE=${1%/*}
    MASKSIZE=${1#*/}

    [ "$MASKSIZE" -lt 8 ] && { echo "Max range is /8."; exit 1; }

    MASK=$(( 0xFFFFFFFF << (32 - "$MASKSIZE") ))

    IFS=. read -r a b c d <<< "$BASE"

    IP=$(( (b << 16) + (c << 8) + d ))

    IPSTART=$(( IP & MASK ))
    IPEND=$(( (IPSTART | ~MASK ) & 0x7FFFFFFF ))

    seq "$IPSTART" "$IPEND" | while read -r i; do
        LAST=$(( i & 0x00FF ))
        if [ $LAST -ne 0 ] && [ $LAST -ne 255 ]; then
            echo "$a.$(( (i & 0xFF0000) >> 16 )).$(( (i & 0xFF00) >> 8 )).$LAST"
        fi
    done
}

SetClientIPv4(){
    # SetClientIPv4 wg0
    for i in $(PrintIPs "$(ReadConfig Address $1)"); do
        DEFAULT="$i"
        grep -q "$i" "$1" || break
    done

    ReadInput "Choose client IPv4" "$DEFAULT"
}

SetClientIPv6(){
    VAL=$(head -c 2 /dev/random | od -A n -t x2 | tr -d " ") # random
}

ShowQR(){
    # ShowQR <wg_interface> <client_name>
    /usr/bin/qrencode -t ansiutf8 < "$CFG"
}

List(){
    # client names, IP, last connect/handshake
    Print "aaa" "RED"
}

WritePeerConfig(){
    # WritePeerConfig section value file
}

Add(){
    [[ ! "$2" ]] && exit # must specify client name

    if [ "$(grep -i $2 /etc/wireguard/$3.conf)" ]; then
        Print "Client already exists\\n" "red"
        exit
    fi

    PRIVKEY="$(/usr/bin/wg genkey)"
    TMP=$(mktemp)
    curl -so "$TMP" "$TEMPLATEURL/peer.conf"
    WritePeerConfig Alias "$2" "$TMP"
    WritePeerConfig PrivateKey "$PRIVKEY" "$TMP"
    WritePeerConfig PublicKey "$(/usr/bin/wg pubkey <<< $PRIVKEY)" "$TMP"
    SetClientIPv4 && WritePeerConfig AllowedIPs "$VAL" "$TMP"
    # add ipv6

    ReadInput "PreSharedKey" ""
    WritePeerConfig PreSharedKey "$VAL" "$TMP"
    
    # show generated config and ask user confirmation
    # appending server config and apply new config
    tee "$TMP" >> "/etc/wireguard/$3.conf" #&& rm -rf "$TMP"
    wg addconf "$3" <(wg-quick strip "$3")
}

Del(){
    # CHECK CLIENT EXISTENCE
    # prompt asking confirmation
    # REMOVE CLIENT FROM CONFIG FILE
    wg set wg0 peer "PUBKEY" remove
    wg syncconf wg0 <(wg-quick strip wg0)
}

ModifyClientEntry(){
    # for enabling and disabling
    # CHECK CLIENT EXISTENCE
    # EDIT FILE
    # prompt asking confirmation
    wg set wg0 peer "PUBKEY" remove
    wg syncconf wg0 <(wg-quick strip wg0)
}

Run "$@"